const STORE={products:'bf_products_v2',cart:'bf_cart_v2',wish:'bf_wish_v2',orders:'bf_orders_v2',coupons:'bf_coupons_v2',settings:'bf_settings_v2',admin:'bf_admin_logged'};
const defaultProducts=[
{id:1,name:'Full Sleeve Cover Shirt',price:40,category:'Women',badge:'Summer',image:'images/Full Sleeve Cover Shirt.jpg'},
{id:2,name:'Volunteer Half Blue',price:35,category:'Men',badge:'Street',image:'images/Volunteer Half Blue.webp'},
{id:3,name:'Double Yellow Shirt',price:36,category:'Women',badge:'Casual',image:'images/DoubleYellowShirt.jpg'},
{id:4,name:'Long Belly Grey Pant',price:32,category:'Women',badge:'Popular',image:'images/Long Belly Grey Pant.avif'},
{id:5,name:'Basic White Shoes',price:48,category:'Shoes',badge:'Basic',image:'images/BasicWhiteShoes.avif'},
{id:6,name:'Woolen Hat',price:18,category:'Accessories',badge:'Best',image:'images/Woolen Hat.jpg'},
{id:7,name:'Black Street Hoodie',price:52,category:'Men',badge:'New',image:'images/Black Street Hoodie.webp'},
{id:8,name:'Kids Soft Tee',price:20,category:'Kids',badge:'Kids',image:'images/Kids Soft Tee.webp'},
{id:9,name:'Butter Tote Bag',price:22,category:'Accessories',badge:'Bag',image:'images/ButterToteBag.webp'}];
const defaultCoupons=[{code:'BUTTER10',discount:10},{code:'WELCOME5',discount:5}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const products=()=>{let p=read(STORE.products,null);if(!p){save(STORE.products,defaultProducts);return defaultProducts}return p};
const cart=()=>read(STORE.cart,[]),wish=()=>read(STORE.wish,[]),orders=()=>read(STORE.orders,[]),coupons=()=>{let c=read(STORE.coupons,null);if(!c){save(STORE.coupons,defaultCoupons);return defaultCoupons}return c};
const money=n=>new Intl.NumberFormat('en-LK',{style:'currency',currency:'LKR',maximumFractionDigits:0}).format(Number(n||0)*365);
function safeImg(img){img.onerror=null;img.src='images/Butter_logo.png';img.classList.add('fallback-img')}
function counts(){let cc=cart().reduce((t,i)=>t+i.qty,0);let wc=wish().length;$$('#cartCount').forEach(e=>e.textContent=cc);$$('#wishCount').forEach(e=>e.textContent=wc)}
function productCard(p){return `<article class="product"><div class="product-img"><span class="badge">${p.badge||p.category}</span><img src="${p.image}" alt="${p.name}" onerror="safeImg(this)"></div><div class="product-body"><h3>${p.name}</h3><p class="price">${money(p.price)}</p><div class="product-actions"><button onclick="addCart(${p.id})">Add to cart</button><button title="Wishlist" onclick="addWish(${p.id})">♡</button></div></div></article>`}
function addCart(id){let c=cart(),item=c.find(x=>x.id===id);item?item.qty++:c.push({id,qty:1});save(STORE.cart,c);counts();toast('Added to cart')}
function addWish(id){let w=wish();if(!w.includes(id))w.push(id);save(STORE.wish,w);counts();toast('Added to wishlist')}
function removeWish(id){save(STORE.wish,wish().filter(x=>x!==id));renderWishlist();counts()}
function removeCart(id){save(STORE.cart,cart().filter(x=>x.id!==id));renderCart();renderCheckout();counts()}
function changeQty(id,delta){let c=cart().map(i=>i.id===id?{...i,qty:Math.max(1,i.qty+delta)}:i);save(STORE.cart,c);renderCart();renderCheckout();counts()}
function toast(msg){let t=document.createElement('div');t.textContent=msg;t.style.cssText='position:fixed;bottom:22px;left:50%;transform:translateX(-50%);background:#111;color:#fff;padding:12px 18px;border-radius:999px;z-index:99;font-weight:800;box-shadow:0 10px 30px #0003';document.body.appendChild(t);setTimeout(()=>t.remove(),1500)}
function renderShop(){let el=$('#shopProducts');if(!el)return;let cats=['All',...new Set(products().map(p=>p.category))];let sel=$('#categoryFilter');if(sel&&!sel.dataset.done){sel.innerHTML=cats.map(c=>`<option value="${c}">${c}</option>`).join('');sel.dataset.done='1';sel.onchange=renderShop}let search=$('#searchBox');if(search&&!search.dataset.done){search.oninput=renderShop;search.dataset.done='1'}let q=(search?.value||'').toLowerCase(),cat=sel?.value||'All';let list=products().filter(p=>(cat==='All'||p.category===cat)&&p.name.toLowerCase().includes(q));el.innerHTML=list.length?list.map(productCard).join(''):'<div class="empty">No products found.</div>'}
function renderCollections(){let el=$('#collectionCards'),admin=$('#adminCategories');let cats=[...new Set(products().map(p=>p.category))];let html=cats.map(c=>`<a class="collection-card" href="index.html#shop" onclick="localStorage.setItem('bf_jump_cat','${c}')"><b>${c}</b><span>${products().filter(p=>p.category===c).length} products</span><small>Explore →</small></a>`).join('');if(el)el.innerHTML=html;if(admin)admin.innerHTML=html}
function applyJumpCat(){let v=localStorage.getItem('bf_jump_cat');if(v&&$('#categoryFilter')){localStorage.removeItem('bf_jump_cat');$('#categoryFilter').value=v;renderShop()}}
function renderWishlist(){let el=$('#wishlistProducts');if(!el)return;let ids=wish(),items=products().filter(p=>ids.includes(p.id));el.innerHTML=items.length?items.map(p=>`<article class="product"><div class="product-img"><img src="${p.image}" alt="${p.name}" onerror="safeImg(this)"></div><div class="product-body"><h3>${p.name}</h3><p class="price">${money(p.price)}</p><div class="product-actions"><button onclick="addCart(${p.id})">Add to cart</button><button onclick="removeWish(${p.id})">Remove</button></div></div></article>`).join(''):'<div class="empty">Your wishlist is empty.</div>'}
function cartRows(){let total=0;let rows=cart().map(i=>{let p=products().find(x=>x.id===i.id);if(!p)return'';total+=p.price*i.qty;return{html:`<div class="cart-row"><div class="row-main"><img src="${p.image}" alt="${p.name}" onerror="safeImg(this)"><div><b>${p.name}</b><p>${money(p.price)} × ${i.qty}</p></div></div><div class="row-actions"><button onclick="changeQty(${p.id},-1)">−</button><button onclick="changeQty(${p.id},1)">+</button><button onclick="removeCart(${p.id})">Remove</button></div></div>`,total}});return{html:rows.map(r=>r.html).join(''),total}}
function renderCart(){let el=$('#cartItems');if(!el)return;let r=cartRows();el.innerHTML=r.html||'<div class="empty">Your cart is empty.</div>';if($('#subtotal'))$('#subtotal').textContent=money(r.total)}
function renderCheckout(){let el=$('#checkoutItems');if(!el)return;let total=0;let html=cart().map(i=>{let p=products().find(x=>x.id===i.id);if(!p)return'';total+=p.price*i.qty;return`<div class="checkout-item"><span>${p.name} × ${i.qty}</span><b>${money(p.price*i.qty)}</b></div>`}).join('');el.innerHTML=html||'<div class="empty">No items in cart.</div>';$('#checkoutTotal').textContent=money(total)}
function checkoutSubmit(){let f=$('#checkoutForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();if(!cart().length)return toast('Cart is empty');let code=($('#couponCode').value||'').trim().toUpperCase();let discount=(coupons().find(c=>c.code===code)?.discount)||0;let subtotal=cart().reduce((t,i)=>{let p=products().find(x=>x.id===i.id);return t+(p?p.price*i.qty:0)},0);let total=subtotal*(1-discount/100);let order={id:Date.now(),date:new Date().toLocaleString(),name:$('#customerName').value,email:$('#customerEmail').value,phone:$('#customerPhone').value,address:$('#customerAddress').value,items:cart(),subtotal,total,discount,status:'Pending'};save(STORE.orders,[order,...orders()]);save(STORE.cart,[]);counts();renderCheckout();toast('Order placed successfully');setTimeout(()=>location.href='dashboard.html',700)}}
function requireAdmin(){if(location.pathname.endsWith('dashboard.html')&&localStorage.getItem(STORE.admin)!=='true')location.href='login.html'}
function login(){let f=$('#loginForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();if($('#loginEmail').value==='admin@butter.lk'&&$('#loginPassword').value==='admin123'){localStorage.setItem(STORE.admin,'true');location.href='dashboard.html'}else toast('Wrong login details')}}
function dashboardTabs(){$$('.side-nav button').forEach(btn=>btn.onclick=()=>{$$('.side-nav button').forEach(b=>b.classList.remove('active'));$$('.dash-tab').forEach(t=>t.classList.remove('active'));btn.classList.add('active');$(`#tab-${btn.dataset.tab}`).classList.add('active')})}
function renderAdmin(){if(!$('#adminProducts'))return;let ps=products(),os=orders();$('#statProducts').textContent=ps.length;$('#statOrders').textContent=os.length;$('#statCustomers').textContent=new Set(os.map(o=>o.email)).size;$('#statRevenue').textContent=money(os.reduce((t,o)=>t+(o.total||0),0));$('#adminProducts').innerHTML=ps.map(p=>`<div class="admin-row"><div class="row-main"><img src="${p.image}" alt="${p.name}" onerror="safeImg(this)"><div><b>${p.name}</b><p>${p.category} • ${money(p.price)}</p></div></div><button class="btn light" onclick="deleteProduct(${p.id})">Delete</button></div>`).join('')||'<div class="empty">No products.</div>';$('#adminOrders').innerHTML=os.map(o=>`<div class="admin-row"><div><b>#${o.id} • ${o.name}</b><p>${o.email} • ${o.phone}<br>${o.date} • Discount ${o.discount}%</p></div><b>${money(o.total)}</b></div>`).join('')||'<div class="empty">No orders yet.</div>';$('#adminCustomers').innerHTML=[...new Map(os.map(o=>[o.email,o])).values()].map(o=>`<div class="admin-row"><div><b>${o.name}</b><p>${o.email} • ${o.phone}</p></div><span>${o.address}</span></div>`).join('')||'<div class="empty">No customers yet.</div>';$('#adminCoupons').innerHTML=coupons().map(c=>`<div class="admin-row"><b>${c.code}</b><span>${c.discount}% off</span></div>`).join('')}
function productAdminForm(){let f=$('#productForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();let p={id:Date.now(),name:$('#pName').value,price:Number($('#pPrice').value),category:$('#pCategory').value,badge:$('#pBadge').value||'New',image:$('#pImage').value||'images/Butter_logo.png'};save(STORE.products,[p,...products()]);f.reset();renderAdmin();renderCollections();toast('Product added')}}
function deleteProduct(id){save(STORE.products,products().filter(p=>p.id!==id));renderAdmin();renderShop();renderCollections()}
function couponForm(){let f=$('#couponForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();save(STORE.coupons,[{code:$('#couponName').value.toUpperCase(),discount:Number($('#couponDiscount').value)},...coupons()]);f.reset();renderAdmin();toast('Coupon added')}}
function settingsForm(){let f=$('#settingsForm');if(!f)return;let s=read(STORE.settings,{});$('#storeName').value=s.name||'';$('#storeEmail').value=s.email||'';$('#storeNote').value=s.note||'';f.onsubmit=e=>{e.preventDefault();save(STORE.settings,{name:$('#storeName').value,email:$('#storeEmail').value,note:$('#storeNote').value});toast('Settings saved')}}
function nav(){let b=$('#menuBtn'),n=$('#mainNav');if(b&&n)b.onclick=()=>n.classList.toggle('show');$('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();toast('Message saved for demo')});$('#logoutBtn')?.addEventListener('click',()=>{localStorage.removeItem(STORE.admin);location.href='login.html'})}
document.addEventListener('DOMContentLoaded',()=>{requireAdmin();nav();counts();renderShop();renderCollections();setTimeout(applyJumpCat,10);renderWishlist();renderCart();renderCheckout();checkoutSubmit();login();dashboardTabs();renderAdmin();productAdminForm();couponForm();settingsForm()});
